### ISSUE TITLE
[Setup] Uninstalling does not remove downloaded files.

### ISSUE THREAD

**Issue by SmilerRyan** [DcmanProductions/Artifact-Journey-Unraveled#1]
After installation and launch, the game files (or updates) are downloaded.
Using the uninstaller does not delete the game directory when uninstalling.

**Files from the launcher directory install/uninstall correctly:**
%LocalAppData%\Programs\artifactlauncher

**The game files are still left in the folder to be manually removed:**
%AppData%\Lost and Found Interactive\Artifact

**Comment by Drew-Chase** [comment]
Unfortunately  that is due to the way in which I process the updates and the installation.  Which is out of my control due to the use of Electron Builder Package Installer.
